version: '3.8'

services:
  # the frontend-backend API
  frontend_API:
    image: box_frontend_api
    ports:
      - 5000:5000 # for http requests
    # for db access
    environment:
      - POSTGRES_USER=${DB_UNAME}
      - POSTGRES_PASSWORD=${DB_PSSWD}
      - POSTGRES_HOST=database

  # the ingest microservice
  ingest:
    image: box_ingest
    ports:
      - 50051:50051 # for box communication
    volumes:
      # for binary box data
      - type: bind
        source: user_data
        target: /user_data

  # the database
  database:
    image: postgres
    # login data passthrough
    environment:
      - POSTGRES_USER=${DB_UNAME}
      - POSTGRES_PASSWORD=${DB_PSSWD}
    ports:
      - '5432:5432' # database interface
    volumes: 
      - db:/var/lib/postgresql/data # data persistance
      - ./init_db.sql:/docker-entrypoint-initdb.d/create_tables.sql # initial config

  # the script executor
  script_executor:
    image: python:3.8-slim
    environment:
      - POSTGRES_USER=${DB_UNAME}
      - POSTGRES_PASSWORD=${DB_PSSWD}
      - POSTGRES_HOST=database
    depends_on:
      - database
    volumes:
      - ./extract_trips.py:/extract_trips.py
      - ./forza_data:/forza_data
    command: sh -c "pip install psycopg2-binary && python /extract_trips.py"

volumes:
  # databse persitancy
  db:
    driver: local
  # volume for /forza_data directory
  forza_data:
